config/routes.rb
Rails.application.routes.draw do
  get 'addbook' => 'books#new'
  
  get 'index' => 'books#index'

  resources :books

  root 'pages#overview'

end

app/models/book.rb
class Book < ActiveRecord::Base
  
  validates_uniqueness_of :title, scope: :author
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    @book = Book.new
  end
  
  def index
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Book added!"
      redirect_to index_path
    else
      render 'new'
    end
  end
  
  private
    
    def book_params
      params.require(:book).permit(:title, :author)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def overview
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book.html.erb
<li>
  <%= book.title %>      <%= book.author %>
</li>

app/views/books/index.html.erb
<% provide(:title, "All books") %>
<h1>All books</h1>

<ul class="books">
  <%= render @books %>
</ul>

app/views/books/new.html.erb
<% provide(:title, "Add Book") %>
<h1>Add a book</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@book) do |f| %>
      <%= render 'shared/error_messages' %>
    
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      
      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>
      
      <%= f.submit "Add book", class: 'btn btn-primary' %>
    <% end %>      
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/overview.html.erb
<% provide(:title, "Overview") %>
<h1>Overview</h1>

<div class="row">
  <div class="col-md-2 col-md-offset-5">
    <%= link_to "Add Book", addbook_path, class: "btn btn-primary btn-lg btn-block" %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@book.errors.count, "error") %>.
    </div>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>